Context: parameters relevant to the propagation of the West Nile Virus.

Years: 2017 to 2024

Months: July to September

Aggregation: yearly mean (July to September only for each year).

Parameters: 
* Climate -> Relative Humidity (2m), Precipitation, Max Temperature (2m), Min Temperature (2m), Wind Speed (10m). 
* Water -> Land Surface Temperature Day, Land Surface Temperature Night, Chlorophyll
* NDVI (mean) -> Agricultural (or croplands/farmlands), Forested land cover (Deciduous forest, Evergreen forest, Mixed forest), Rangeland (Grassland, Shrubland, Pasture, Natural grazing land) 

Region: County-level in the United States.

In [1]:
import pandas as pd
import geopandas as gpd

import numpy as np
import os
import time
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from datetime import datetime

### OpenMeteo API - Obtainable Parameters:
* Climate -> Relative Humidity (2m), Precipitation, Max Temperature (2m), Min Temperature (2m), Wind Speed (10m). 
* Need source geoids (county fips codes) and the corresponding lat/lon using the TIGER API.

In [2]:
CENSUS_COUNTIES = "https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_county_500k.zip"
# connecticut used counties up until 2022, then switched to planning regions, which my WNV case data reflects
# thus, I will get the lat/lon and corresponding data for both time periods (and FIPS code variations). 
LEGACY_COUNTIES_CT = "https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_county_500k.zip"

In [3]:
df_all = pd.read_csv("https://raw.githubusercontent.com/Amoreno73/wnv_embeddings/refs/heads/main/notebooks/national_embeddings/national_wnv_case_data/all_data_normalized.csv")
df_all["GEOID"] = df_all["GEOID"].astype(str).str.zfill(5)
counties = gpd.read_file(CENSUS_COUNTIES).to_crs(4326)
legacy_counties = gpd.read_file(LEGACY_COUNTIES_CT).to_crs(4326)

In [4]:
legacy_subset = legacy_counties[legacy_counties["GEOID"].str.startswith("09")]

In [5]:
all_counties = pd.concat([counties, legacy_subset], ignore_index=True)
all_counties # now includes both legacy and new fips codes for CT

,STATEFP,COUNTYFP,COUNTYNS,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,STATE_NAME,LSAD,ALAND,AWATER,geometry,AFFGEOID
0,01,003,00161527,0500000US01003,01003,Baldwin,Baldwin County,AL,Alabama,06,4117725048,1132887203,"POLYGON ((-88.02858 30.22676, -88.02399 30.230...",NaN
1,01,069,00161560,0500000US01069,01069,Houston,Houston County,AL,Alabama,06,1501742235,4795415,"POLYGON ((-85.71209 31.19727, -85.70934 31.198...",NaN
2,01,005,00161528,0500000US01005,01005,Barbour,Barbour County,AL,Alabama,06,2292160151,50523213,"POLYGON ((-85.74803 31.61918, -85.74544 31.618...",NaN
3,01,119,00161585,0500000US01119,01119,Sumter,Sumter County,AL,Alabama,06,2340898915,24634880,"POLYGON ((-88.41492 32.36452, -88.41471 32.366...",NaN
4,05,091,00069166,0500000US05091,05091,Miller,Miller County,AR,Arkansas,06,1616257232,36848741,"POLYGON ((-94.04343 33.55158, -94.04332 33.552...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,09,011,00212799,NaN,09011,New London,NaN,NaN,NaN,06,1722716728,276657755,"POLYGON ((-72.46673 41.5839, -72.42886 41.5889...",0500000US09011
3239,09,005,00212796,NaN,09005,Litchfield,NaN,NaN,NaN,06,2384116952,62334525,"POLYGON ((-73.51795 41.67086, -73.51678 41.687...",0500000US09005
3240,09,013,00212668,NaN,09013,Tolland,NaN,NaN,NaN,06,1062807467,17549693,"POLYGON ((-72.51733 41.8699, -72.51692 41.8736...",0500000US09013
3241,09,015,00212801,NaN,09015,Windham,NaN,NaN,NaN,06,1328478475,21477921,"POLYGON ((-72.25208 41.72706, -72.25264 41.728...",0500000US09015
3242,09,003,00212338,NaN,09003,Hartford,NaN,NaN,NaN,06,1903543897,40543777,"POLYGON ((-73.02054 42.00009, -73.00876 42.038...",0500000US09003

In [6]:
all_counties.columns

Index(['STATEFP', 'COUNTYFP', 'COUNTYNS', 'GEOIDFQ', 'GEOID', 'NAME',
       'NAMELSAD', 'STUSPS', 'STATE_NAME', 'LSAD', 'ALAND', 'AWATER',
       'geometry', 'AFFGEOID'],
      dtype='str')

In [7]:
# Ensure county geometries are in WGS84 first
all_counties = all_counties.to_crs("EPSG:4326")

# Compute centroids in projected CRS, then convert back to WGS84 for API
centroids = all_counties.to_crs("EPSG:5070").geometry.centroid.to_crs("EPSG:4326")

all_counties["longitude"] = centroids.x
all_counties["latitude"] = centroids.y

# Hard guard before requests
bad = all_counties[
    ~all_counties["latitude"].between(-90, 90) |
    ~all_counties["longitude"].between(-180, 180)
]
assert bad.empty, f"Invalid lat/lon rows found: {len(bad)}"

In [8]:
cols_to_keep = ['GEOID', 'NAME', 'STUSPS', 'STATE_NAME',
       'geometry', 'latitude', 'longitude']

all_counties = all_counties[cols_to_keep]

In [9]:
# keep only the ones present in the national WNV embedding analysis. 
counties_interest = [c for c in set(all_counties["GEOID"]) if c in set(df_all["GEOID"])]
len(counties_interest)

3150

In [10]:
all_counties = all_counties[all_counties["GEOID"].isin(counties_interest)]
all_counties

,GEOID,NAME,STUSPS,STATE_NAME,geometry,latitude,longitude
0,01003,Baldwin,AL,Alabama,"POLYGON ((-88.02858 30.22676, -88.02399 30.230...",30.727083,-87.722293
1,01069,Houston,AL,Alabama,"POLYGON ((-85.71209 31.19727, -85.70934 31.198...",31.153231,-85.302390
2,01005,Barbour,AL,Alabama,"POLYGON ((-85.74803 31.61918, -85.74544 31.618...",31.869536,-85.393439
3,01119,Sumter,AL,Alabama,"POLYGON ((-88.41492 32.36452, -88.41471 32.366...",32.590808,-88.198762
4,05091,Miller,AR,Arkansas,"POLYGON ((-94.04343 33.55158, -94.04332 33.552...",33.312183,-93.892121
...,...,...,...,...,...,...,...
3238,09011,New London,NaN,NaN,"POLYGON ((-72.46673 41.5839, -72.42886 41.5889...",41.486562,-72.101497
3239,09005,Litchfield,NaN,NaN,"POLYGON ((-73.51795 41.67086, -73.51678 41.687...",41.792223,-73.245412
3240,09013,Tolland,NaN,NaN,"POLYGON ((-72.51733 41.8699, -72.51692 41.8736...",41.854871,-72.336511
3241,09015,Windham,NaN,NaN,"POLYGON ((-72.25208 41.72706, -72.25264 41.728...",41.829889,-71.987442
3242,09003,Hartford,NaN,NaN,"POLYGON ((-73.02054 42.00009, -73.00876 42.038...",41.806230,-72.732865

In [11]:
print(all_counties["latitude"].isna().sum())
print(all_counties["longitude"].isna().sum())

0
0

I will be iterating over `all_counties` to get the mean yearly weather for each `GEOID`, using the Open-Meteo API.

In [13]:
all_counties.to_csv("all_counties.csv")